export const colorMap = {
  black: "Black",
  silver: "Silver",
  gray: "Gray",
  white: "White",
  maroon: "Maroon",
  red: "Red",
  purple: "Purple",
  fuchsia: "Fuchsia",
  green: "Green",
  lime: "Lime",
  olive: "Olive",
  yellow: "Yellow",
  navy: "Navy",
  blue: "Blue",
  teal: "Teal",
  aqua: "Aqua",
  aliceblue: "Alice Blue",
  antiquewhite: "Antique White",
  aquamarine: "Aquamarine",
  azure: "Azure",
  beige: "Beige",
  bisque: "Bisque",
  blanchedalmond: "Blanched Almond",
  blueviolet: "Blue Violet",
  brown: "Brown",
  burlywood: "Burly Wood",
  cadetblue: "Cadet Blue",
  chartreuse: "Chartreuse",
  chocolate: "Chocolate",
  coral: "Coral",
  cornflowerblue: "Cornflower Blue",
  cornsilk: "Cornsilk",
  crimson: "Crimson",
  cyan: "Cyan",
  darkblue: "Dark Blue",
  darkcyan: "Dark Cyan",
  darkgoldenrod: "Dark Goldenrod",
  darkgray: "Dark Gray",
  darkgreen: "Dark Green",
  darkgrey: "Dark Grey",
  darkkhaki: "Dark Khaki",
  darkmagenta: "Dark Magenta",
  darkolivegreen: "Dark Olive Green",
  darkorange: "Dark Orange",
  darkorchid: "Dark Orchid",
  darkred: "Dark Red",
  darksalmon: "Dark Salmon",
  darkseagreen: "Dark Sea Green",
  darkslateblue: "Dark Slate Blue",
  darkslategray: "Dark Slate Gray",
  darkslategrey: "Dark Slate Grey",
  darkturquoise: "Dark Turquoise",
  darkviolet: "Dark Violet",
  deeppink: "Deep Pink",
  deepskyblue: "Deep Sky Blue",
  dimgray: "Dim Gray",
  dimgrey: "Dim Grey",
  dodgerblue: "Dodger Blue",
  firebrick: "Fire Brick",
  floralwhite: "Floral White",
  forestgreen: "Forest Green",
  gainsboro: "Gainsboro",
  ghostwhite: "Ghost White",
  gold: "Gold",
  goldenrod: "Goldenrod",
  greenyellow: "Green Yellow",
  grey: "Grey",
  honeydew: "Honeydew",
  hotpink: "Hot Pink",
  indianred: "Indian Red",
  indigo: "Indigo",
  ivory: "Ivory",
  khaki: "Khaki",
  lavender: "Lavender",
  lavenderblush: "Lavender Blush",
  lawngreen: "Lawn Green",
  lemonchiffon: "Lemon Chiffon",
  lightblue: "Light Blue",
  lightcoral: "Light Coral",
  lightcyan: "Light Cyan",
  lightgoldenrodyellow: "Light Goldenrod Yellow",
  lightgray: "Light Gray",
  lightgreen: "Light Green",
  lightgrey: "Light Grey",
  lightpink: "Light Pink",
  lightsalmon: "Light Salmon",
  lightseagreen: "Light Sea Green",
  lightskyblue: "Light Sky Blue",
  lightslategray: "Light Slate Gray",
  lightslategrey: "Light Slate Grey",
  lightsteelblue: "Light Steel Blue",
  lightyellow: "Light Yellow",
  limegreen: "Lime Green",
  linen: "Linen",
  magenta: "Magenta",
  mediumaquamarine: "Medium Aquamarine",
  mediumblue: "Medium Blue",
  mediumorchid: "Medium Orchid",
  mediumpurple: "Medium Purple",
  mediumseagreen: "Medium Sea Green",
  mediumslateblue: "Medium Slate Blue",
  mediumspringgreen: "Medium Spring Green",
  mediumturquoise: "Medium Turquoise",
  mediumvioletred: "Medium Violet Red",
  midnightblue: "Midnight Blue",
  mintcream: "Mint Cream",
  mistyrose: "Misty Rose",
  moccasin: "Moccasin",
  navajowhite: "Navajo White",
  oldlace: "Old Lace",
  olivedrab: "Olive Drab",
  orange: "Orange",
  orangered: "Orange Red",
  orchid: "Orchid",
  palegoldenrod: "Pale Goldenrod",
  palegreen: "Pale Green",
  paleturquoise: "Pale Turquoise",
  palevioletred: "Pale Violet Red",
  papayawhip: "Papaya Whip",
  peachpuff: "Peach Puff",
  peru: "Peru",
  pink: "Pink",
  plum: "Plum",
  powderblue: "Powder Blue",
  rosybrown: "Rosy Brown",
  royalblue: "Royal Blue",
  saddlebrown: "Saddle Brown",
  salmon: "Salmon",
  sandybrown: "Sandy Brown",
  seagreen: "Sea Green",
  seashell: "Seashell",
  sienna: "Sienna",
  skyblue: "Sky Blue",
  slateblue: "Slate Blue",
  slategray: "Slate Gray",
  slategrey: "Slate Grey",
  snow: "Snow",
  springgreen: "Spring Green",
  steelblue: "Steel Blue",
  tan: "Tan",
  thistle: "Thistle",
  tomato: "Tomato",
  turquoise: "Turquoise",
  violet: "Violet",
  wheat: "Wheat",
  whitesmoke: "White Smoke",
  yellowgreen: "Yellow Green",
  rebeccapurple: "Rebecca Purple",
};

